user_controller:
    resource: "@UserBundle/Controller"
    prefix:   /
    type: annotation

ino:
    resource: "@InoBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
