# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        UserBundle\Entity\User: bcrypt

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
#        in_memory:
#            memory:
#                users:
#                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        our_database_users:
            entity: { class: UserBundle:User, property: username}

    firewalls:
        secured_area:
            pattern:    ^/
            form_login:
                check_path: login
                login_path: login
            logout:
                path:   logout
                target: articles
            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
# authenticate in controllers
#            - { path: ^/article/new, roles: ROLE_USER }
#            - { path: ^/article/edit, roles: ROLE_USER }
#            - { path: ^/article/remove, roles: ROLE_USER }