services:
#    ino.example:
#        class: InoBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
  model.product:
    class: InoBundle\Services\ProductModel
    arguments: ["@doctrine.orm.entity_manager"]